services:
  - type: web
    name: gymza-saas
    env: node
    plan: free
    buildCommand: npm install && npm install --prefix server
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        fromContext: env
      - key: REDIS_URL
        fromContext: env
      - key: JWT_ACCESS_SECRET
        fromContext: env
      - key: JWT_REFRESH_SECRET
        fromContext: env
      - key: CLIENT_ORIGIN
        value: https://gymza-nine.vercel.app,https://gymza-omega.vercel.app,https://gymza-saas-app.onrender.com
      - key: VITE_API_URL
        value: /api
      - key: VITE_SOCKET_URL
        value: https://gymza-saas-app.onrender.com
