import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Settings, Shield, Bell, Smartphone, Globe, Save } from 'lucide-react';
const SettingsPage = () => {
    return (_jsxs("div", { children: [_jsxs("div", { className: "page-header", style: { marginBottom: '2rem' }, children: [_jsx("h1", { children: "Settings" }), _jsx("p", { className: "text-muted", children: "Manage your gym profile and application preferences." })] }), _jsxs("div", { className: "glass-panel", style: { display: 'grid', gridTemplateColumns: '250px 1fr', minHeight: '600px', overflow: 'hidden' }, children: [_jsx("div", { style: { borderRight: '1px solid var(--clr-glass-border)', padding: '1.5rem' }, children: _jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: '0.5rem' }, children: [_jsxs("button", { className: "nav-item active", style: { width: '100%', justifyContent: 'flex-start' }, children: [_jsx(Settings, { size: 18 }), "General"] }), _jsxs("button", { className: "nav-item", style: { width: '100%', justifyContent: 'flex-start' }, children: [_jsx(Shield, { size: 18 }), "Security"] }), _jsxs("button", { className: "nav-item", style: { width: '100%', justifyContent: 'flex-start' }, children: [_jsx(Bell, { size: 18 }), "Notifications"] }), _jsxs("button", { className: "nav-item", style: { width: '100%', justifyContent: 'flex-start' }, children: [_jsx(Smartphone, { size: 18 }), "Integrations"] }), _jsxs("button", { className: "nav-item", style: { width: '100%', justifyContent: 'flex-start' }, children: [_jsx(Globe, { size: 18 }), "Billing"] })] }) }), _jsxs("div", { style: { padding: '2.5rem' }, children: [_jsx("h2", { style: { fontSize: '1.25rem', marginBottom: '2rem' }, children: "General Settings" }), _jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: '2rem', maxWidth: '600px' }, children: [_jsxs("div", { className: "form-group", children: [_jsx("label", { className: "form-label", children: "Gym Name" }), _jsx("input", { className: "form-input", placeholder: "Gymza Fitness Center" })] }), _jsxs("div", { className: "form-group", children: [_jsx("label", { className: "form-label", children: "Contact Email" }), _jsx("input", { className: "form-input", placeholder: "contact@gymza.com" })] }), _jsxs("div", { className: "form-group", children: [_jsx("label", { className: "form-label", children: "Business Address" }), _jsx("textarea", { className: "form-input", rows: 3, placeholder: "123 Fitness St, Workout City, WC 12345", style: { resize: 'none' } })] }), _jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1.5rem', background: 'var(--clr-bg-input)', borderRadius: '12px' }, children: [_jsxs("div", { children: [_jsx("h3", { style: { fontSize: '0.9rem', fontWeight: '600' }, children: "Dark Mode" }), _jsx("p", { style: { fontSize: '0.8rem', color: 'var(--clr-text-muted)' }, children: "Use the high-contrast dark theme" })] }), _jsx("div", { style: {
                                                    width: '44px',
                                                    height: '24px',
                                                    background: 'var(--clr-primary)',
                                                    borderRadius: '100px',
                                                    position: 'relative',
                                                    cursor: 'pointer'
                                                }, children: _jsx("div", { style: {
                                                        width: '18px',
                                                        height: '18px',
                                                        background: 'white',
                                                        borderRadius: '50%',
                                                        position: 'absolute',
                                                        right: '3px',
                                                        top: '3px'
                                                    } }) })] }), _jsx("div", { style: { display: 'flex', justifyContent: 'flex-end', marginTop: '1rem' }, children: _jsxs("button", { className: "btn btn-primary", style: { padding: '0.75rem 2rem' }, children: [_jsx(Save, { size: 18 }), "Save Changes"] }) })] })] })] })] }));
};
export default SettingsPage;
